os: osx
language: cpp
compiler: clang
before_install:
  # Fix stupid Homebrew issue with gcc vs oclint
  # https://github.com/travis-ci/travis-ci/issues/8826
  - brew cask uninstall oclint
install:
  - export HOMEBREW_NO_AUTO_UPDATE=1
  - brew update
  - formulas="cmake pkg-config fftw libiconv libusb libbladerf airspy hackrf ffmpeg librtlsdr nanomsg qt boost";
    echo "Dependencies: $formulas";
    for f in $formulas; do
        echo "Checking dependency $f... ";
        if brew ls --versions $f >/dev/null; then
            echo "already installed";
            echo "Checking whether dependency $f is outdated... ";
            if ! brew outdated $f; then
                echo "yes";
                echo "Upgrading dependency $f...";
                brew upgrade $f;
            else
                echo "no";
            fi;
        else
            echo "not installed";
            echo "Installing dependency $f...";
            brew install $f;
        fi;
    done
script:
  - mkdir build
  - cd build
  - Qt5Core_DIR=/usr/local/opt/qt cmake
        -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG
        -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG
        -DCMAKE_INSTALL_PREFIX=$(brew --prefix)
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_FIND_FRAMEWORK=LAST
        -DCMAKE_VERBOSE_MAKEFILE=ON
        -Wno-dev
        ..
