os: osx
language: cpp
compiler: clang
before_install:
  # Fix stupid Homebrew issue with gcc vs oclint
  # https://github.com/travis-ci/travis-ci/issues/8826
  - brew cask uninstall oclint
install:
  - export HOMEBREW_NO_AUTO_UPDATE=1
  - brew tap pothosware/pothos
  - brew update
  - formulas="cmake pkg-config fftw libiconv libusb libbladerf airspy hackrf ffmpeg librtlsdr nanomsg qt boost opencv limesuite libmirisdr libairspyhf";
    for f in $formulas; do
        if brew ls --versions $f >/dev/null; then
            if ! brew outdated $f; then
                brew upgrade $f;
            fi;
        else
            brew install $f;
        fi;
    done
script:
  - mkdir build
  - cd build
  - CMAKE_PREFIX_PATH=/usr/local/opt/qt cmake
        -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG
        -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG
        -DCMAKE_INSTALL_PREFIX=$(brew --prefix)
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_FIND_FRAMEWORK=LAST
        -DCMAKE_VERBOSE_MAKEFILE=ON
        -Wno-dev
        ..
  - make
  - make install
